import express from 'express';
import { ResourceController } from '../controllers/ResourceController';

const router = express.Router();

/**
 * Resource Hub API Routes
 * Serves German vocabulary data generated by the Data Factory
 */

// Get all available CEFR levels
router.get('/levels', ResourceController.getLevels);

// Get summary for a specific level
router.get('/:level/summary', ResourceController.getLevelSummary);

// Get all topics for a specific level
router.get('/:level/topics', ResourceController.getTopics);

// Get vocabulary data for a specific level and topic
router.get('/:level/:topic', ResourceController.getTopicData);

// Admin: Clear cache
router.post('/cache/clear', ResourceController.clearCache);

export default router;
